//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Armage
{
	public static class HeightMapGen
	{
		public const int erodePasses = 10;

		public static HeightMap GenBasicTerrainMap(HeightmapProperties heightProps, int seed) {
			HeightMap h = new HeightMap(heightProps.size, seed);
			h.AddPerlinNoise(heightProps.perlinFreq);
			h.Perturb(heightProps.perturb, heightProps.perturb);
			for (int i = 0; i < HeightMapGen.erodePasses; i++ )
				h.Erode(heightProps.erode);
			h.Smoothen();

			return h;
		}
	}
}

