//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace Armage
{
	public class NameFeed
	{
		public Dictionary<string, string[]> interchangeables;
		public string[] prefixes;
		public string[] postfixes;

		public NameFeed ()
		{
			definePrefixes();
			definePostfixes();
			defineInterchangeables();
		}

		protected virtual void definePrefixes() {
			prefixes = new string[] { "kon", "egla", "uotra", "ujcre", "crua", "osmx",
				"whalsa", "bowa", "ubli", "eofre", "druin", "eias", "baal", "ogro", "broa", "choe", "okku",
				"stric", "eiyu", "gaia", "gamma", "alpha", "omega", "zeta", "trias", "eblaa", "iiota",
				"ichigara", "malpho", "mormada", "alsota", "eito", "pajaka", "crawm", "perti", "ghro",
				"ayon", "spher", "yuion", "traxis", "lambosi", "tryo", "zciu", "wer", "tram",
				"terio", "pro", "pal", "byo", "bio", "bional", "trul", "hyo", "rastol", "ramso", "latos", "xiona", "xioo",
				"xoiu", "gerto", "gras", "gramas", "itto", "timauo", "lloiu", "proas", "prixus", "prid", "arla", "awral",
				"atera", "ackaar", "trama", "duura", "plato", "razxixn", "ssamax", "xniyxzo", "oukoo", "roosz", "orphii"
			};
		}

		protected virtual void definePostfixes() {
			postfixes = new string[] { "ionus", "icos", "auoron", "auro", "ryou", "tron", "artron", "tromas",
				"tas", "ban", "itan", "gaan", "gaam", "guil", "quil", "quas", "quaxion", "xius", "siox", "skon", "xxii",
				"ixx", "protus", "artus", "armaas", "irot", "rotto", "guu", "graas", "tamio", "eau", "vous", "zxz", "ixxzi",
				"oria", "haria", "ius", "morias", "darian", "ordesius", "malfan", "rastiko", "tika", "aiio", "allaxis",
				"yyioto", "raxsamatra", "abblax", "jamax", "xxsito", "rellio", "stama", "qur", "leo", "ncer", "kuilla",
				"aquo", "asos", "usas", "iatas", "pantria", "talaras", "juila", "iaga", "eao", "euima", "stalama", "photon",
				"ostrus", "mormalus", "yuio", "huulon", "roto", "arheetus", "ghuu", "prong", "ightzbx", "zxixymosz", "driu",
				"werts", "artoria", "amodo", "llaas"
			};
		}

		protected virtual void defineInterchangeables() {
			interchangeables =  new Dictionary<string, string[]>();
			interchangeables["a"] = new string[] { "a", "a", "a", "a", "ai", "ai", "ai", "ay", "ay",
				"aye", "ae", "ae", "ae", "ia", "eu", "i", "iae",
				"aieau", "aeau", "au", "aui" };
			interchangeables["b"] = new string[] { "b", "b", "b", "b", "t", "t", "t", "p", "p",
				"p", "ba", "be", "bai", "by", "bi", "be", "bjo",
				"bo", "pe", "pa", "pi", "pau", "peo", "peau", "pio",
				"ju", "je", "j", "g", "c", "k" };
			interchangeables["c"] = new string[] { "c", "c", "c", "c", "k", "k", "k", "k", "kt",
				"ck", "ck", "t", "t", "p", "p", "sk", "sck",
				"q", "q", "x", "x", "xx", "xk", "cx", "cx",
				"tx", "ca", "co", "ci", "ce", "cu" };
			interchangeables["d"] = new string[] { "d", "d", "d", "d", "t", "t", "t", "b", "b",
				"b", "do", "da", "de", "di", "dr", "k", "k",
				"ck", "q", "g", "g", "p", "p" };
			interchangeables["e"] = new string[] { "e", "e", "e", "e", "a", "a", "ea", "ea", "ea",
				"eau", "eei", "eai", "aei", "i", "ek", "ec", "eye",
				"eye", "ey", "eu", "eio", "er", "et", "en", "em",
				"ep", "eg", "ed", "es", "ess", "ex" };
			interchangeables["f"] = new string[] { "f", "f", "f", "f", "h", "h", "fl", "fe", "fer",
				"far", "fre", "fra", "fy", "fu", "fo", "foo", "fea",
				"fi", "l", "ll", "v", "v", "vo", "vi", "vu",
				"va", "ve", "vea", "vuo", "voi" };
			interchangeables["g"] = new string[] { "g", "g", "g", "g", "d", "d", "t", "t", "j",
				"j", "ge", "gre", "ga", "gra", "gru", "gr", "gr",
				"b", "gi", "ji", "jo", "go", "gor", "guo", "gio",
				"gl", "gl" };
			interchangeables["h"] = new string[] { "h", "h", "h", "h", "sh", "sh", "sh", "sw", "swe",
				"swa", "sha", "shi", "sho", "sc", "sck", "sca", "sce",
				"hi", "ha", "huo", "hio", "heau", "hea", "hye", "hai",
				"haou", "ht", "hre", "hnn", "hk" };
			interchangeables["i"] = new string[] { "i", "i", "i", "i", "ii", "ii", "ie", "ie", "io",
				"ia", "eia", "eye", "y", "y", "y", "yi", "yi",
				"ai", "ai", "aie", "ih", "il", "ill", "ir", "irr",
				"iw", "in", "im", "iq", "ixx" };
			interchangeables["j"] = new string[] { "j", "j", "j", "j", "ja", "ja", "jaa", "ji", "jo",
				"g", "g", "juu", "guu", "go", "gu", "jye", "jio",
				"je", "ger", "jer", "jar", "jir", "je", "jel", "jk",
				"jck", "jah", "jv" };
			interchangeables["k"] = new string[] { "k", "k", "k", "k", "ck", "ck", "cc", "kk", "kt",
				"kp", "ka", "ka", "ke", "ke", "ko", "ki", "kii",
				"kuu", "kui", "ker", "kar", "ky", "key", "kai", "koo",
				"keo", "kx", "krn" };
			interchangeables["l"] = new string[] { "l", "l", "l", "l", "ll", "ll", "ll", "la", "la",
				"le", "lo", "loo", "li", "lii", "ler", "lar", "lu",
				"luu", "lam", "leum", "leun", "lan", "lun", "lin", "lim",
				"lum", "lop", "lox" };
			interchangeables["m"] = new string[] { "m", "m", "m", "m", "n", "n", "mn", "mn", "mb",
				"mb", "mb", "hm", "hm", "mo", "ma", "me", "mi",
				"mas", "mes", "mos", "mc", "mk", "mck", "ms", "mss",
				"mz", "mzx", "mizx" };
			interchangeables["n"] = new string[] { "n", "n", "n", "n", "m", "m", "mn", "mn", "nd",
				"nd", "nd", "ny", "ln", "in", "na", "ne", "ni",
				"nas", "nek", "nos", "nc", "nk", "nck", "nj", "njs",
				"nz", "nizx" };
			interchangeables["o"] = new string[] { "o", "o", "o", "o", "aio", "yo", "aio", "yuo", "uo",
				"io", "ao", "oo", "uoo", "auo", "oy", "om", "omn",
				"on", "or", "os", "oh", "ho", "hoo", "aeo", "ox",
				"oz", "oxx" };
			interchangeables["p"] = new string[] { "p", "p", "p", "p", "g", "g", "g", "b", "b",
				"b", "pu", "po", "pao", "pem", "pii", "pio", "pai",
				"pra", "pru", "par", "par", "py", "py", "px", "pk",
				"pt", "pz", "pyx" };
			interchangeables["q"] = new string[] { "q", "q", "q", "q", "k", "k", "k", "k", "qc",
				"quc", "qac", "qy", "quo", "qui", "qua", "qyo", "qii",
				"qry", "qre", "qt", "qta", "qty", "qlo", "ql", "qs",
				"qz", "qxx", "qzx" };
			interchangeables["r"] = new string[] { "r", "r", "r", "r", "ra", "ri", "ro", "roi", "re",
				"ruu", "rau", "rji", "rjo", "ryua", "rye", "rie", "rie",
				"rey", "ray", "rp", "rl", "rll", "rv", "rev", "ran",
				"ras", "rz", "ryx" };
			interchangeables["s"] = new string[] { "s", "s", "s", "s", "sh", "sh", "sh", "sp", "sp",
				"sp", "sx", "sx", "sj", "sji", "sw", "swa", "swe",
				"swea", "swee", "seer", "sai", "say", "sii", "syu", "sa",
				"syx", "sxx", "szx" };
			interchangeables["t"] = new string[] { "t", "t", "t", "t", "tt", "tt", "tt", "yt", "pt",
				"pt", "rt", "rt", "it", "it", "at", "ot", "to",
				"tuu", "tar", "tra", "tr", "tri", "traa", "trio", "try",
				"tas", "ter", "ttx" };
			interchangeables["u"] = new string[] { "u", "u", "u", "u", "uv", "uv", "uv", "um", "un",
				"uk", "ur", "uro", "ura", "uy", "uou", "uio", "uer",
				"uear", "uf", "uj", "ul", "uln", "uli", "url", "uw",
				"us", "uz", "ux" };
			interchangeables["v"] = new string[] { "v", "v", "v", "v", "uv", "uv", "uv", "wv", "wv",
				"vu", "vuu", "ov", "yv", "ouv", "eav", "uyv", "vy",
				"vyio", "ver", "var", "vro", "vrl", "vom", "van", "vee",
				"vss", "vz", "vzx" };
			interchangeables["w"] = new string[] { "w", "w", "w", "w", "we", "wi", "wii", "wo", "wou",
				"wau", "wia", "wio", "yw", "ew", "ow", "owo", "ewe",
				"eiw", "yuw", "uyw", "rw", "rwo", "rwi", "rwii", "rwa",
				"vw", "vww", "wz" };
			interchangeables["x"] = new string[] { "x", "x", "x", "x", "xy", "xyo", "xi", "xii", "xii",
				"xuu", "xas", "xs", "xs", "xss", "xss", "xt", "xte",
				"xti", "xto", "xp", "xl", "xll", "xv", "xc", "xck",
				"xk", "xkk", "xzk" };
			interchangeables["y"] = new string[] { "y", "y", "y", "y", "yv", "yve", "yuu", "yii", "yio",
				"yea", "ya", "yaa", "yi", "yer", "yr", "yt", "yh",
				"yun", "yum", "yjio", "yji", "yjo", "ylk", "yk", "yr",
				"yrs", "yrzx", "yree" };
			interchangeables["z"] = new string[] { "z", "z", "z", "z", "s", "s", "s", "sz", "szz",
				"szx", "sxi", "zxi", "zsx", "zx", "zo", "zi", "zii",
				"zu", "zuu", "zuoi", "zao", "zeau", "zai", "zom", "zv",
				"zw", "zwo", "zxk" };
		}
	}
}
