//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace Armage
{
	public class OceanProperties
	{
		public Texture2D texture;
		public Vector2 textureScale;
		public Material material;
		public Vector3 scale;

		public OceanProperties(string texture, Vector2 textureScale, string material, Vector3 scale) {
			this.texture = Resources.Load<Texture2D> (texture);
			this.textureScale = textureScale;
			this.material = Resources.Load<Material> (material);
			this.scale = scale;
		}

		public OceanProperties shallowClone() {
			return (OceanProperties) this.MemberwiseClone();
		}
	}
}

