//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Armage
{
	public struct SphereProperties
	{
		public float radius;
		public int longitude;
		public int latitude;

		public SphereProperties(float radius, int longitude, int latitude) {
			this.radius = radius;
			this.longitude = longitude;
			this.latitude = latitude;
		}

		public SphereProperties shallowClone() {
			return (SphereProperties) this.MemberwiseClone();
		}
	}
}

